In [32]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
def loadGlove(path):
    file = open(path,'r')
    model = {}
    for l in file:
        line = l.split()
        word = line[0]
        value = np.array([float(val) for val in line[1:]])
        model[word] = value
    return model

glove = loadGlove('glove.6B.50d.txt')

In [33]:
glove['python']

array([ 0.5897  , -0.55043 , -1.0106  ,  0.41226 ,  0.57348 ,  0.23464 ,
       -0.35773 , -1.78    ,  0.10745 ,  0.74913 ,  0.45013 ,  1.0351  ,
        0.48348 ,  0.47954 ,  0.51908 , -0.15053 ,  0.32474 ,  1.0789  ,
       -0.90894 ,  0.42943 , -0.56388 ,  0.69961 ,  0.13501 ,  0.16557 ,
       -0.063592,  0.35435 ,  0.42819 ,  0.1536  , -0.47018 , -1.0935  ,
        1.361   , -0.80821 , -0.674   ,  1.2606  ,  0.29554 ,  1.0835  ,
        0.2444  , -1.1877  , -0.60203 , -0.068315,  0.66256 ,  0.45336 ,
       -1.0178  ,  0.68267 , -0.20788 , -0.73393 ,  1.2597  ,  0.15425 ,
       -0.93256 , -0.15025 ])

In [35]:
cosine_similarity(glove['cat'].reshape(1, -1), glove['dog'].reshape(1, -1))

array([[0.92180053]])

In [37]:
cosine_similarity(glove['cat'].reshape(1, -1), glove['piano'].reshape(1, -1))

array([[0.19825255]])

In [38]:
predicted_king_embedding = glove['queen'] - glove['woman'] + glove['man']
cosine_similarity(predicted_king_embedding.reshape(1, -1), glove['king'].reshape(1, -1))

array([[0.85888392]])

In [46]:
predicted_emphasis_embedding_1 = glove['softer'] - glove['soft']
predicted_emphasis_embedding_2 = glove['darker'] - glove['dark']
cosine_similarity(predicted_emphasis_embedding_1.reshape(1, -1), predicted_emphasis_embedding_2.reshape(1, -1))

array([[0.52087747]])